apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: production
data:
  APP_ENV: "production"
  APP_NAME: "backendApp"
  LOG_LEVEL: "info"
  API_BASE_URL: "https://api.mattaudu.xyz"
  FEATURE_X_ENABLED: "true"
