name: production-cd

on:
  workflow_dispatch:

jobs:
  Build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: "Create version number"
        run: |
         echo "VERSION_NUMBER=v1.0.$GITHUB_RUN_NUMBER" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t backend-app:${{ env.VERSION_NUMBER }} ./backend

      - name: "Tag Docker Images"
        run: |
          docker tag backend-app:${{env.VERSION_NUMBER}} ${{ secrets.DOCKER_HUB_USERNAME }}/backend-app:${{env.VERSION_NUMBER}}
    
      - name: Log in to Docker Hub
        uses: docker/login-action@v3 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: "Push to Docker Hub"
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/backend-app:${{env.VERSION_NUMBER}}